BootStrap: docker
From: continuumio/miniconda3:4.3.27

################################################################################
%setup
################################################################################

################################################################################
%post
################################################################################

cat <<END_OF_ENV > /opt/rnaseq_env.yml
name: rnaseq
channels:
  -  bioconda
  -  defaults
dependencies:
  -  argh=0.26.1
  -  bcftools=1.5
  -  bioconductor-annotate
  -  bioconductor-annotationdbi
  -  bioconductor-biobase
  -  bioconductor-biocgenerics
  -  bioconductor-biocparallel
  -  bioconductor-biomart
  -  bioconductor-biostrings
  -  bioconductor-deseq2
  -  bioconductor-edger
  -  bioconductor-genefilter
  -  bioconductor-geneplotter
  -  bioconductor-genomeinfodb
  -  bioconductor-genomicalignments
  -  bioconductor-genomicfeatures
  -  bioconductor-genomicranges
  -  bioconductor-iranges
  -  bioconductor-limma
  -  bioconductor-noiseq
  -  bioconductor-rsamtools
  -  bioconductor-rtracklayer
  -  bioconductor-s4vectors
  -  bioconductor-summarizedexperiment
  -  bioconductor-tximport
  -  bioconductor-xvector
  -  bioconductor-zlibbioc
  -  bx-python
  -  expat
  -  fastqc
  -  gffutils
  -  htslib
  -  java-jdk
  -  libxml2
  -  perl-threaded
  -  pyfaidx
  -  pysam
  -  qualimap
  -  r-bh
  -  r-car
  -  r-catools
  -  r-data.table
  -  r-digest=0.6.12
  -  r-dplyr=0.5.0
  -  r-futile.logger=1.4.1
  -  r-futile.options=1.0.0
  -  r-getopt=1.20.0
  -  r-ggplot2=2.2.1
  -  r-gplots=2.17.0
  -  r-htmltools=0.3
  -  r-htmlwidgets=0.5
  -  r-knitr=1.12.3
  -  r-lambda.r=1.1.7
  -  r-locfit=1.5_9.1
  -  r-magrittr=1.5
  -  r-psych=1.5.8
  -  r-purrr=0.2.2
  -  r-readr=0.2.2
  -  r-reshape2=1.4.2
  -  r-rjson=0.2.15
  -  r-scales=0.4.1
  -  r-snow=0.4_1
  -  r-stringr=1.1.0
  -  r-tibble=1.2
  -  r-yaml=2.1.13
  -  rseqc=2.6.4
  -  samtools=1.5
  -  simplejson=3.8.1
  -  stringtie=1.3.3
  -  trimmomatic=0.36
  -  argcomplete=1.0.0
  -  bzip2=1.0.6
  -  cairo=1.14.8
  -  cffi=1.9.1
  -  cryptography=1.7.1
  -  curl=7.52.1
  -  cython=0.25.2
  -  dbus=1.10.10
  -  enum34=1.1.6
  -  fontconfig=2.12.1
  -  freetype=2.5.5
  -  glib=2.50.2
  -  gsl=2.2.1
  -  gst-plugins-base=1.8.0
  -  gstreamer=1.8.0
  -  harfbuzz=0.9.39
  -  icu=54.1
  -  idna=2.2
  -  ipaddress=1.0.18
  -  jbig=2.1
  -  jpeg=9b
  -  libffi=3.2.1
  -  libgcc=5.2.0
  -  libiconv=1.14
  -  libpng=1.6.27
  -  libsodium=1.0.10
  -  libtiff=4.0.6
  -  libuuid=1.0.3
  -  libxcb=1.12
  -  mkl=2017.0.1
  -  ncurses=5.9
  -  numpy=1.12.1
  -  openssl=1.0.2k
  -  pango=1.40.3
  -  pcre=8.39
  -  pip=9.0.1
  -  pixman=0.34.0
  -  pyasn1=0.1.9
  -  pycosat=0.6.1
  -  pycparser=2.17
  -  pyopenssl=16.2.0
  -  python=2.7.13
  -  qt=5.6.2
  -  r=3.3.1
  -  r-acepack=1.3_3.3
  -  r-assertthat=0.1
  -  r-base=3.3.1
  -  r-base64enc=0.1_3
  -  r-bitops=1.0_6
  -  r-boot=1.3_18
  -  r-broom=0.4.1
  -  r-caret=6.0_70
  -  r-class=7.3_14
  -  r-cluster=2.0.5
  -  r-codetools=0.2_15
  -  r-colorspace=1.3_1
  -  r-crayon=1.3.1
  -  r-curl=2.3
  -  r-dbi=0.5_1
  -  r-dichromat=2.0_0
  -  r-essentials=1.4.3
  -  r-evaluate=0.10
  -  r-forcats=0.1.1
  -  r-foreach=1.4.3
  -  r-foreign=0.8_67
  -  r-formatr=1.4
  -  r-formula=1.2_1
  -  r-gdata=2.17.0
  -  r-gistr=0.3.6
  -  r-glmnet=2.0_5
  -  r-gridextra=2.2.1
  -  r-gtable=0.2.0
  -  r-gtools=3.5.0
  -  r-haven=1.0.0
  -  r-hexbin=1.27.1
  -  r-highr=0.6
  -  r-hmisc=3.17_4
  -  r-hms=0.3
  -  r-httpuv=1.3.3
  -  r-httr=1.2.1
  -  r-irdisplay=0.4.3
  -  r-irkernel=0.7
  -  r-iterators=1.0.8
  -  r-jsonlite=1.1
  -  r-kernsmooth=2.23_15
  -  r-labeling=0.3
  -  r-lattice=0.20_34
  -  r-latticeextra=0.6_28
  -  r-lazyeval=0.2.0
  -  r-lme4=1.1_12
  -  r-lubridate=1.6.0
  -  r-maps=3.1.0
  -  r-markdown=0.7.7
  -  r-mass=7.3_45
  -  r-matrix=1.2_7.1
  -  r-matrixmodels=0.4_1
  -  r-memoise=1.0.0
  -  r-mgcv=1.8_12
  -  r-mime=0.5
  -  r-minqa=1.2.4
  -  r-mnormt=1.5_5
  -  r-modelr=0.1.0
  -  r-munsell=0.4.3
  -  r-nlme=3.1_128
  -  r-nloptr=1.0.4
  -  r-nnet=7.3_12
  -  r-openssl=0.9.5
  -  r-pbdzmq=0.2_3
  -  r-pbkrtest=0.4_6
  -  r-plogr=0.1_1
  -  r-plyr=1.8.4
  -  r-pryr=0.1.2
  -  r-quantmod=0.4_7
  -  r-quantreg=5.26
  -  r-r6=2.2.0
  -  r-randomforest=4.6_12
  -  r-rbokeh=0.4.2
  -  r-rcolorbrewer=1.1_2
  -  r-rcpp=0.12.8
  -  r-rcpparmadillo=0.7.100.3.1
  -  r-rcppeigen=0.3.2.8.1
  -  r-rcurl=1.95_4.8
  -  r-readxl=0.1.1
  -  r-recommended=3.3.1
  -  r-repr=0.7
  -  r-rmarkdown=0.9.6
  -  r-rpart=4.1_10
  -  r-rsqlite=1.1_1
  -  r-rvest=0.3.2
  -  r-selectr=0.3_0
  -  r-shiny=0.13.2
  -  r-sparsem=1.7
  -  r-spatial=7.3_11
  -  r-stringi=1.1.2
  -  r-survival=2.39_4
  -  r-tidyr=0.6.0
  -  r-tidyverse=1.0.0
  -  r-ttr=0.23_1
  -  r-uuid=0.1_2
  -  r-xml=3.98_1.5
  -  r-xml2=1.0.0
  -  r-xtable=1.8_2
  -  r-xts=0.9_7
  -  r-zoo=1.7_13
  -  readline=6.2
  -  requests=2.12.4
  -  ruamel_yaml=0.11.14
  -  setuptools=27.2.0
  -  six=1.10.0
  -  sqlite=3.13.0
  -  tk=8.5.18
  -  wheel=0.29.0
  -  xz=5.2.2
  -  yaml=0.1.6
  -  zeromq=4.1.5
  -  zlib=1.2.8
prefix: /opt/conda/envs/rnaseq
END_OF_ENV


cat > /etc/locale.gen <<EOF
en_US.UTF-8 UTF-8
EOF
apt-get update
apt-get -y install locales zip

###
### conda environment with common packages
###
export PATH=/opt/conda/bin:$PATH
cd /opt
[ -f rnaseq_env.yml ] || exit 1

# create the rnaseq environment
conda update --all --yes --quiet
conda env create --quiet -n rnaseq -f rnaseq_env.yml

# clean up so image can be shrunk
conda clean --all --yes

###
### install hisat2, salmon, and subread - all from binary packages
###
wget ftp://ftp.ccb.jhu.edu/pub/infphilo/hisat2/downloads/hisat2-2.1.0-Linux_x86_64.zip
unzip hisat2-2.1.0-Linux_x86_64.zip
rm -f hisat2-2.1.0-Linux_x86_64.zip

wget https://github.com/COMBINE-lab/salmon/releases/download/v0.9.1/Salmon-0.9.1_linux_x86_64.tar.gz
tar -xzf Salmon-0.9.1_linux_x86_64.tar.gz
rm -f Salmon-0.9.1_linux_x86_64.tar.gz

wget -O subread-1.6.0-Linux-x86_64.tar.gz \
  https://sourceforge.net/projects/subread/files/subread-1.6.0/subread-1.6.0-Linux-x86_64.tar.gz/download
tar -xzf subread-1.6.0-Linux-x86_64.tar.gz
rm -f subread-1.6.0-Linux-x86_64.tar.gz

# create generic mount points for the workflow
mkdir /data /resources

# set up the environment for the container
################################################################################
%environment
################################################################################
export SINGULARITY_INIT=1
PATH="/opt/conda/envs/rnaseq/bin:/opt/conda/bin:/bin:/usr/bin"
PATH="${PATH}:/opt/hisat2-2.1.0:/opt/Salmon-latest_linux_x86_64/bin"
PATH="${PATH}:/opt/subread-1.6.0-Linux-x86_64/bin"
export PS1="Singularity.$SINGULARITY_CONTAINER> $PS1"
export LANG=en_US.UTF-8
export CONTAINER_VER=0.3
export CONDA_DEFAULT_ENV=rnaseq
export CONDA_PREFIX=/opt/conda/envs/rnaseq
export ANACONDA_HOME=/opt/conda

################################################################################
%runscript
################################################################################

# In this case using the runscript only for self documentation.

cat <<EOF

------------------------------------------------------------
rnaseq - rnaseq pipeline tools version $CONTAINER_VER
------------------------------------------------------------

This container encapsulates tools for RNA-Seq analysis.
It is intended for creating reproducible pipelines.


################################################################################
%test
################################################################################
. /.singularity.d/env/90-environment.sh
conda list
featureCounts -v
hisat2 --version
salmon --version
samtools --version
